-- Add reviews table for expanded UI functionality and test coverage
-- Run this in Supabase SQL Editor if not already done

CREATE TABLE IF NOT EXISTS public.reviews (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  rating integer not null check (rating >= 1 and rating <= 5),
  comment text,
  created_at timestamptz default now()
);

ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;

-- Policies for stable, realistic access control
CREATE POLICY "Anyone can read reviews" ON public.reviews
  FOR SELECT USING (true);

CREATE POLICY "Users can create their own reviews" ON public.reviews
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own reviews" ON public.reviews
  FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own reviews" ON public.reviews
  FOR DELETE USING (auth.uid() = user_id);

-- Optional seed (uncomment and adjust IDs after products and users exist)
-- INSERT INTO public.reviews (product_id, user_id, rating, comment) VALUES
-- (1, (SELECT id FROM auth.users WHERE email = 'alice@example.com' LIMIT 1), 5, 'Excellent Python guide!');