-- ============================================
-- Teststand — Supabase Schema
-- Для миграции Flask teststand на Supabase + GitHub Pages
-- ============================================

-- 1. PRODUCTS (публичный каталог, без владельца)
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text not null,
  price numeric(10,2) not null,
  created_at timestamptz default now()
);

-- 2. API_ITEMS (для практики API автотестов)
create table if not exists public.api_items (
  id bigint generated by default as identity primary key,
  title text not null,
  description text default '',
  category text default 'general',
  user_id uuid references auth.users(id) on delete cascade not null,
  created_at timestamptz default now()
);

-- 3. CART_ITEMS
create table if not exists public.cart_items (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  product_id bigint references public.products(id) on delete cascade not null,
  quantity integer not null default 1,
  unique(user_id, product_id)
);

-- 4. ORDERS + ORDER_ITEMS
create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  order_number text unique not null,
  total numeric(10,2) not null,
  created_at timestamptz default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint references public.orders(id) on delete cascade not null,
  product_id bigint references public.products(id),
  quantity integer not null,
  price numeric(10,2) not null
);

-- ============================================
-- Включаем Row Level Security (RLS)
-- ============================================
alter table public.products enable row level security;
alter table public.api_items enable row level security;
alter table public.cart_items enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

-- ============================================
-- POLICIES (правила доступа)
-- ============================================

-- PRODUCTS: все могут читать (даже не авторизованные)
create policy "Products are publicly readable"
  on public.products
  for select
  using (true);

-- API_ITEMS: все читают, только владелец пишет/меняет/удаляет
create policy "Anyone can read api_items"
  on public.api_items
  for select
  using (true);

create policy "Users can insert their own api_items"
  on public.api_items
  for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own api_items"
  on public.api_items
  for update
  using (auth.uid() = user_id);

create policy "Users can delete their own api_items"
  on public.api_items
  for delete
  using (auth.uid() = user_id);

-- CART: только владелец своей корзины
create policy "Users manage their own cart"
  on public.cart_items
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- ORDERS: только свои заказы
create policy "Users can view their own orders"
  on public.orders
  for select
  using (auth.uid() = user_id);

create policy "Users can create their own orders"
  on public.orders
  for insert
  with check (auth.uid() = user_id);

-- ORDER_ITEMS: только для своих заказов
create policy "Users manage order items of their orders"
  on public.order_items
  for all
  using (exists (
    select 1 from public.orders
    where orders.id = order_items.order_id
      and orders.user_id = auth.uid()
  ));

-- ============================================
-- SEED: продукты (каталог)
-- ============================================
insert into public.products (name, description, price)
values
  ('Python Handbook', 'A concise guide to Python programming.', 29.99),
  ('Playwright in Action', 'End-to-end testing with Playwright.', 39.99),
  ('API Testing Cookbook', 'Recipes for REST API test automation.', 24.99),
  ('Test Data Builder', 'Patterns for predictable test fixtures.', 19.99),
  ('Locators Guide', 'Stable selectors for UI automation.', 14.99)
on conflict do nothing;

-- ============================================
-- Примечание:
-- api_items засеиваем позже (после создания пользователей alice/bob),
-- потому что нужен user_id (uuid из auth.users)
-- ============================================
