-- ============================================
-- Teststand — Supabase Schema
-- Для миграции Flask teststand на Supabase + GitHub Pages
-- ============================================

-- 1. PRODUCTS (публичный каталог, без владельца)
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text not null,
  price numeric(10,2) not null,
  category text default 'general',
  created_at timestamptz default now()
);

-- 2. API_ITEMS (для практики API автотестов)
create table if not exists public.api_items (
  id bigint generated by default as identity primary key,
  title text not null,
  description text default '',
  category text default 'general',
  user_id uuid references auth.users(id) on delete cascade not null,
  created_at timestamptz default now()
);

-- 3. CART_ITEMS
create table if not exists public.cart_items (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  product_id bigint references public.products(id) on delete cascade not null,
  quantity integer not null default 1,
  unique(user_id, product_id)
);

-- 4. ORDERS + ORDER_ITEMS
create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  order_number text unique not null,
  total numeric(10,2) not null,
  status text not null default 'completed',
  created_at timestamptz default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint references public.orders(id) on delete cascade not null,
  product_id bigint references public.products(id),
  quantity integer not null,
  price numeric(10,2) not null
);

-- ============================================
-- Включаем Row Level Security (RLS)
-- ============================================
alter table public.products enable row level security;
alter table public.api_items enable row level security;
alter table public.cart_items enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

-- ============================================
-- POLICIES (правила доступа)
-- ============================================

-- PRODUCTS: все могут читать (даже не авторизованные)
create policy "Products are publicly readable"
  on public.products
  for select
  using (true);

-- Allow adding products via the "API Items" UI (teststand feature: api items service adds to catalog)
create policy "Anyone can insert products (via API Items add-to-catalog)"
  on public.products
  for insert
  with check (true);

-- API_ITEMS: все читают, только владелец пишет/меняет/удаляет
create policy "Anyone can read api_items"
  on public.api_items
  for select
  using (true);

create policy "Users can insert their own api_items"
  on public.api_items
  for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own api_items"
  on public.api_items
  for update
  using (auth.uid() = user_id);

create policy "Users can delete their own api_items"
  on public.api_items
  for delete
  using (auth.uid() = user_id);

-- CART: только владелец своей корзины
create policy "Users manage their own cart"
  on public.cart_items
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- ORDERS: только свои заказы
create policy "Users can view their own orders"
  on public.orders
  for select
  using (auth.uid() = user_id);

create policy "Users can create their own orders"
  on public.orders
  for insert
  with check (auth.uid() = user_id);

-- ORDER_ITEMS: только для своих заказов
create policy "Users manage order items of their orders"
  on public.order_items
  for all
  using (exists (
    select 1 from public.orders
    where orders.id = order_items.order_id
      and orders.user_id = auth.uid()
  ));

-- ============================================
-- SEED: продукты (каталог электроники)
-- ============================================
-- Категории: phones, tablets, laptops (минимум 5 товаров в каждой)
DELETE FROM public.products;

insert into public.products (name, description, price, category)
values
  -- Phones
  ('Apple iPhone 16', 'Latest iPhone with powerful A18 chip and excellent camera.', 999.00, 'phones'),
  ('Samsung Galaxy S25 Ultra', 'Premium flagship with S Pen and top-tier display.', 1199.00, 'phones'),
  ('Google Pixel 9 Pro', 'Best-in-class camera and clean Android experience.', 899.00, 'phones'),
  ('OnePlus 13', 'Blazing fast performance and rapid charging.', 799.00, 'phones'),
  ('Xiaomi 15 Pro', 'High-end specs at competitive price.', 699.00, 'phones'),

  -- Tablets
  ('Apple iPad Pro 13"', 'M4 chip, stunning Liquid Retina XDR display.', 1299.00, 'tablets'),
  ('Samsung Galaxy Tab S10+', 'Large vibrant AMOLED screen for media and work.', 1099.00, 'tablets'),
  ('Lenovo Tab P12 Pro', 'Great for drawing, reading and entertainment.', 649.00, 'tablets'),
  ('Microsoft Surface Pro 11', 'Windows 11 tablet with excellent keyboard support.', 999.00, 'tablets'),
  ('Huawei MatePad Pro 12.2', 'Premium build quality and stylus precision.', 749.00, 'tablets'),

  -- Laptops
  ('Apple MacBook Air M3 13"', 'Lightweight, powerful and long battery life.', 1099.00, 'laptops'),
  ('Dell XPS 14', 'Premium ultrabook with gorgeous InfinityEdge display.', 1399.00, 'laptops'),
  ('Lenovo ThinkPad X1 Carbon', 'Business laptop with legendary keyboard.', 1599.00, 'laptops'),
  ('HP Spectre x360 14"', 'Versatile 2-in-1 convertible laptop.', 1199.00, 'laptops'),
  ('ASUS Zenbook 14 OLED', 'Stunning OLED display and premium aluminum body.', 949.00, 'laptops')
on conflict do nothing;

-- ============================================
-- Примечание:
-- api_items засеиваем позже (после создания пользователей alice/bob),
-- потому что нужен user_id (uuid из auth.users)
--
-- Добавление через UI "My API Items" теперь также создаёт запись в products (каталог).
-- Для этого нужна политика INSERT на products (добавлена выше).
-- ============================================

-- ============================================
-- DEMO SEED: sample orders (run manually after you have users)
-- Replace '00000000-0000-0000-0000-000000000000' with a real auth.users.id
-- (you can get it from auth.users or after logging in via UI)
-- ============================================
-- Example (uncomment and replace UUID):
-- INSERT INTO public.orders (user_id, order_number, total, status, created_at)
-- VALUES
--   ('<USER_UUID_HERE>', 'ORD-123456', 124.50, 'completed', now() - interval '5 days'),
--   ('<USER_UUID_HERE>', 'ORD-234567', 59.98, 'completed', now() - interval '2 days')
-- ON CONFLICT DO NOTHING;
--
-- Then add items (replace order_id):
-- INSERT INTO public.order_items (order_id, product_id, quantity, price)
-- SELECT o.id, p.id, 2, p.price FROM public.orders o, public.products p
-- WHERE o.order_number = 'ORD-123456' AND p.name LIKE '%Playwright%' LIMIT 1;
-- ... repeat for other items
-- ============================================
